### ISSUE TITLE
Replace hard coded bot id strings

### ISSUE THREAD

**Issue by cnsumner** [cnsumner/huldra#8]
There are a couple of places left in the code where I forgot to swap out the hard coded bot ID with variables.  This would prevent the bot from working properly if anyone other than me tried to deploy it.

In both of the below cases, `674451490743779339` needs to be changed to `${bot.self.id.id}`

https://github.com/cnsumner/huldra/blob/00a0c46f72c4a4eaee79c6666df7da95c8607b65/lib/huldra.dart#L161
https://github.com/cnsumner/huldra/blob/00a0c46f72c4a4eaee79c6666df7da95c8607b65/lib/huldra.dart#L300

**Comment by sumitsawant** [comment]
@cnsumner I'll fix this , please assign this to me .

**Comment by cnsumner** [comment]
@sumitsawant you got it.

**Comment by sumitsawant** [comment]
@cnsumner I have made the changes . Please have a look and let me if there are any changes required from my side .

**Comment by cnsumner** [comment]
@sumitsawant a small change is needed. Look at the comment on the PR.

**Comment by cnsumner** [comment]
@sumitsawant go ahead and rebase your branch onto master to fix the conflicts (I forgot I had format-on-save enabled and I merged a commit that changed all the formatting) and then we'll be all set.

**Comment by sumitsawant** [comment]
@cnsumner I have attached new PR by fixing conflicts please have a look and let me know .

**Comment by cnsumner** [comment]
@sumitsawant approved and merged. Thank you!
